Refresh templates by sending SIGUSR2
FRosner/cluster-broccoli pull request #255
Opened 2017-07-24 14:57 UTC by Gerrrr

Solves #229

2017-07-25 08:15 UTC, swsnr requested changes
Please add API documentation to all template sources and model case classes.

2017-07-25 08:15 UTC, lunaryorn commented on server/src/main/scala/de/frosner/broccoli/services/TemplateService.scala
> +      .loadTemplates()
Please inject this as dependency.

2017-07-25 08:15 UTC, lunaryorn commented on server/src/main/scala/de/frosner/broccoli/controllers/TemplateController.scala
> -  private val templates = templateService.getTemplates
Was this unused?

2017-07-25 08:16 UTC, Gerrrr commented on server/src/main/scala/de/frosner/broccoli/controllers/TemplateController.scala
> -  private val templates = templateService.getTemplates
yes

2017-07-26 11:05 UTC, lunaryorn commented on server/src/main/scala/de/frosner/broccoli/controllers/TemplateController.scala
> -  private val templates = templateService.getTemplates
Okay

2017-07-26 11:06 UTC, swsnr requested changes
Please do not forget to add API documentation for the template source trait and implementations :blush:

2017-07-26 12:15 UTC, swsnr requested changes

2017-07-26 12:15 UTC, lunaryorn commented on server/src/main/scala/de/frosner/broccoli/templates/SignalRefreshedTemplateSource.scala
> +@Singleton
Please remove this annotation; it's not used since the source is created through a provider method which has its own `@Singleton` annotation.

2017-07-26 12:15 UTC, lunaryorn commented on server/src/main/scala/de/frosner/broccoli/templates/CachedTemplateSource.scala
> +@Singleton
Please remove this annotation; it's not used since the source is created through a provider method which has its own `@Singleton` annotation.

2017-07-26 12:15 UTC, lunaryorn commented on server/src/main/resources/reference.conf
> +  templates.path = "templates"
Should we perhaps use `./templates` to make clear that it's a path relative to the local directory?

2017-07-26 14:13 UTC, swsnr approved these changes
Thanks am happy now! ☺️

2017-07-27 08:18 UTC, merged