WIP: Input sanitization
FRosner/cluster-broccoli pull request #265
Opened 2017-08-03 11:04 UTC by Gerrrr

#17

2017-08-03 13:16 UTC, swsnr requested changes

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/instances/InstanceModule.scala
> +      case invalidStorageType => throw new IllegalArgumentException("Wrong instance storage type")
Isn't this case unreachable, given that `StorageType` has just two fixed variants?

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/instances/InstanceModule.scala
> +    }
I'm not sure that we really need to use `Try` here given that we just re-throw the exception.

I'd just remove `Try`, create the instance storages directly and let exceptions propagate.  They'll end up in the logger anyway.

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/instances/InstanceModule.scala
> +class InstanceModule extends AbstractModule with ScalaModule with Logging {
Do not use the `Logging` trait; I think it's redundant, and I'd like to deprecate it.

Instead just add `private val log = Logger(getClass)` which will create a nicely configured logger automatically.  Then replace all instances of `Logger` in this module with `log`.

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/instances/StorageType.scala
> +sealed abstract class StorageType(override val entryName: String) extends EnumEntry with EnumEntry.Lowercase
Since you're explicitly setting the entry names, ie, have no auto-generated names, you don't need to use `EnumEntry.Lowercase` here.  Just remove it.

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/instances/StorageType.scala
> +  val values = findValues
Please add a type annotation (ie, press `alt + enter`, then select "add type annotation") and `override` here.

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/instances/conf/CouchDBInstanceStorageConfiguration.scala
> +    Logger.info(s"broccoli.instances.storage.couchdb.url=$url")
A simple factory method like this shouldn't have side-effects, not even logging.  Please move these logging calls to the couchdb storage class or to the instances module (wherever they fit best).

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/instances/conf/FileSystemInstanceStorageConfiguration.scala
> +    Logger.info(s"broccoli.instances.storage.fs.url=$url")
Likewise, please move this logging call to the appropriate place (see above).

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/instances/conf/FileSystemInstanceStorageConfiguration.scala
> +object FileSystemInstanceStorageConfiguration extends Logging {
Please remove the logging trait here.

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/instances/conf/CouchDBInstanceStorageConfiguration.scala
> +object CouchDBInstanceStorageConfiguration extends Logging {
Please remove the logging trait here.

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/instances/conf/InstanceConfiguration.scala
> +object InstanceConfiguration extends Logging {
Please remove the logging trait here.

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/instances/conf/InstanceConfiguration.scala
> +    Logger.info(s"Nomad/Consul polling frequency set to $pollingFrequency seconds")
A simple factory method like this shouldn't have side-effects, not even logging. Please move these logging calls to the couchdb storage class or to the instances module (wherever they fit best).

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/instances/conf/InstanceStorageConfiguration.scala
> +object InstanceStorageConfiguration extends Logging {
Please remove the `Logging` trait here, you're not using it in this object.

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/models/Instance.scala
> +      case (key, ParameterInfo(_, _, None, _, _))          => None
Replace with `case (key, info) => info.default.map(Function.const(key))`; that's more straight-forward and easier to read than the complex destructuring in the pattern match.

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/models/ParameterType.scala
> +object ParameterType extends Enum[ParameterType] with PlayJsonEnum[ParameterType] {
Please add API documentation to this type.

Furthermore please remove `PlayJsonEnum`; we never use this enum in JSON, do we?

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/instances/StorageType.scala
> +object StorageType extends Enum[StorageType] with PlayJsonEnum[StorageType] {
Please remove `PlayJsonEnum` here; you never use this enum in JSON, do you?

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/templates/TemplateRenderer.scala
> +    def sanitize(parameter: String, value: String) = {
Please move this to a top-level function in `TemplateRenderer` so that you can test it independently.

2017-08-03 13:16 UTC, swsnr commented on server/src/main/scala/de/frosner/broccoli/instances/InstanceModule.scala
> +    instanceStorage
I wonder why this code uses a `sys.addShutdownHook` in addition to a normal stop hook.  Can you try to find out?

I think we should remove the shutdown hook and just leave the stop hook; it should be sufficient.

I'm also curious why closing the storage runs on a separate thread via `Future.apply` here.  I suggest to just close it right away without wrapping it in a `Future` and then return `Future.successful(())` at the end. The documentation of `addStopHook` explicitly allows this, and we gain nothing with a separate thread here.

2017-08-16 13:25 UTC, swsnr requested changes

2017-08-16 13:25 UTC, lunaryorn commented on .gitignore
> +.idea/*
A `.gitignore` in a repo should normally only contain files being created by the repository itself, ie, build artifacts or local caches.

For IDE metadata the convention is to keep them in your [global ignore file](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore).  

I'd appreciate if you could remove `.idea/` from `.gitignore` again and move it to your own global ignore file.

2017-08-16 13:28 UTC, Gerrrr commented on .gitignore
> +.idea/*
Hey @lunaryorn , 
Thanks for the suggestion, I was not aware of the global ignore file!

2017-08-17 13:50 UTC, lunaryorn commented
@Gerrrr Tell me when you're ready and I'll review.  Perhaps tomorrow?

2017-08-18 08:05 UTC, swsnr requested changes
A few minor changes, but other than that looks good :+1:

2017-08-18 08:05 UTC, lunaryorn commented on server/src/main/scala/de/frosner/broccoli/instances/conf/InstanceConfiguration.scala
> +    log.info(s"Nomad/Consul polling frequency set to $pollingFrequency seconds")
Please remove this logging statement; it doesn't belong here.

If we need to log this for some reason, the class that's using this setting should log it.

2017-08-18 08:05 UTC, lunaryorn commented on server/src/main/scala/de/frosner/broccoli/services/InstanceService.scala
> +  private lazy val pollingFrequencySeconds = instanceConfiguration.pollingFrequency
The instance service uses the polling frequency, so if at all, the instance service should log it.

2017-08-18 08:05 UTC, lunaryorn commented on server/src/main/scala/de/frosner/broccoli/templates/TemplateRenderer.scala
> +  private[templates] def sanitize(parameter: String, value: String, parameterInfos: Map[String, ParameterInfo]) = {
Why `private[templates]`?

2017-08-18 11:29 UTC, Gerrrr commented on server/src/main/scala/de/frosner/broccoli/templates/TemplateRenderer.scala
> +  private[templates] def sanitize(parameter: String, value: String, parameterInfos: Map[String, ParameterInfo]) = {
Because it is a function that it is only used by `renderJson` and not supposed to be public, but I still want to unit test it.

2017-08-18 11:52 UTC, FRosner commented
Hi @Gerrrr. I'd appreciate if we changed the templates in a way that there is at least one example of a real string parameter. Right now all of them are raw but maybe we can add some just for the sake of an example?

2017-08-18 12:18 UTC, lunaryorn commented on server/src/main/scala/de/frosner/broccoli/templates/TemplateRenderer.scala
> +  private[templates] def sanitize(parameter: String, value: String, parameterInfos: Map[String, ParameterInfo]) = {
Why not just make it public?

2017-08-21 11:57 UTC, lunaryorn commented
@Gerrrr I think you need to rebase again; I merged #278 which seems to have triggered a merge conflicts.

Please ping me when you're done and I'll approve this PR.

2017-08-21 11:57 UTC, swsnr submitted a review, later dismissed

2017-08-21 12:14 UTC, FRosner requested changes

2017-08-21 12:14 UTC, FRosner commented on server/src/main/resources/reference.conf
> +  }
- [ ] Now that we have these changes in the `reference.conf` I think it is time to either add the new parameter to the README or change the README to point to the `reference.conf` for configuration reference and remove the long tables I built. If we do that, we should at least put some comments though, so we don't lose any information that is currently provided.
- [ ] We should also add a section to the Wiki migration guide to 0.7.0, explaining the defaultType. 
- [ ] The new option in `meta.json` should also be explained in the Wiki, no?

2017-08-21 14:37 UTC, swsnr requested changes

2017-08-21 14:37 UTC, lunaryorn commented on server/src/main/scala/de/frosner/broccoli/services/InstanceService.scala
> +  }
Uh, why did you move this back?!  You already fixed it, and now unfixed it?

2017-08-21 14:38 UTC, lunaryorn commented on server/src/main/scala/de/frosner/broccoli/services/InstanceService.scala
> +  }
Ah, I see… you removed it from the instance configuration.  Fine with me then.

2017-08-21 14:38 UTC, swsnr submitted a review, later dismissed

2017-08-21 14:46 UTC, Gerrrr commented on server/src/main/resources/reference.conf
> +  }
I've added the new parameter to the README. I will update wiki after merging the PR and before closing the issue. Does it make sense?

2017-08-21 14:54 UTC, lunaryorn commented
@Gerrrr Sure, as far as I'm concerned.

2017-08-22 12:29 UTC, Gerrrr commented on server/src/main/resources/reference.conf
> +  }
yes

2017-08-22 12:39 UTC, swsnr approved these changes

2017-08-22 12:42 UTC, FRosner approved these changes

2017-08-22 12:42 UTC, merged