WIP: Introduce jinjava for template rendering
FRosner/cluster-broccoli pull request #311
Opened 2017-10-29 14:20 UTC by Gerrrr

fixes #224

2017-11-06 16:06 UTC, Gerrrr commented
Can you please review @FRosner ?

2017-11-06 16:56 UTC, FRosner commented
I will take a look tomorrow :)

2017-11-08 10:07 UTC, FRosner commented
Just to check if I understood correctly. We render the template using Jinjava twice:

1. When the template is loaded, we render it without any bindings just to extract the parameters.
2. When the template is rendered, we render with all the bindings to generate the JSON

Will the mechanism of extracting all variables still work even if they are not mentioned in the parameter infos? Will it extract only global (unbound) variables or also local ones (like the ones bound in a loop)?

2017-11-08 10:38 UTC, FRosner commented
I set `convert-dashes-to-underscores = true` and defined two parameters:

- `secret_parameter`
- `secret-parameter` inside an `if`

Then I didn't receive a warning, maybe because the `secret-parameter` is inside the `if`? Is that expectec behaviour?

```
{
    "Job": {
        "Region": "global",
        "ID": "{{id}}",
        "Name": "{{id}}",
        "Type": "service",
        "Priority": 50,
        "AllAtOnce": false,
        "Datacenters": [
            "dc1"
        ],
        "Constraints": null,
        "TaskGroups": [
            {
                "Name": "http-group",
                "Count": 1,
                "Constraints": null,
                "Tasks": [
                    {
                        "Name": "http-task",
                        "Driver": "raw_exec",
                        "User": "",
                        "Config": {
                            "args": [
                                "-m",
                                "SimpleHTTPServer"
                            ],
                            "command": "/usr/bin/python"
                        },
                        "Constraints": null,
                        "Env": null,
                        "Services": [
                            {
                                "Id": "",
                                "Name": "{{id}}-web-ui-1",
                                "Tags": ["protocol-http", "{{secret_parameter}}"],
                                "PortLabel": "ui",
                                "Checks": [
                                    {
                                        "Id": "",
                                        "Name": "service: \"{{id}}-ui-1\" check",
                                        "Type": "http",
                                        "Command": "",
                                        "Args": null,
                                        "Path": "/",
                                        "Protocol": "",
                                        "Interval": 10000000000,
                                        "Timeout": 2000000000
                                    }
                                ]
                            },
                            {
                                "Id": "",
                                "Name": "{{id}}-web-ui-2",
                                "Tags": ["protocol-http"],
                                "PortLabel": "ui",
                                "Checks": [
                                    {
                                        "Id": "",
                                        "Name": "service: \"{{id}}-ui-2\" check",
                                        "Type": "http",
                                        "Command": "",
                                        "Args": null,
                                        "Path": "/doesnotexist",
                                        "Protocol": "",
                                        "Interval": 10000000000,
                                        "Timeout": 2000000000
                                    }
                                ]
                            }
                        ],
                        "Resources": {
                            "CPU": {{cpu}},
                            "MemoryMB": {% if secret-parameter %} 128 {% else %} 256 {% endif %},
                            "DiskMB": 300,
                            "IOPS": 0,
                            "Networks": [
                                {
                                    "Public": false,
                                    "CIDR": "",
                                    "ReservedPorts": [
                                        {
                                            "Label": "ui",
                                            "Value": 8000
                                        }
                                    ],
                                    "DynamicPorts": null,
                                    "IP": "",
                                    "MBits": 10
                                }
                            ]
                        },
                        "Meta": null,
                        "KillTimeout": 5000000000,
                        "LogConfig": {
                            "MaxFiles": 10,
                            "MaxFileSizeMB": 10
                        },
                        "Artifacts": null
                    }
                ],
                "RestartPolicy": {
                    "Interval": 60000000000,
                    "Attempts": 2,
                    "Delay": 15000000000,
                    "Mode": "delay"
                },
                "Meta": null
            }
        ],
        "Update": {
            "Stagger": 0,
            "MaxParallel": 0
        },
        "Periodic": null,
        "Meta": null,
        "Status": "",
        "StatusDescription": "",
        "CreateIndex": 0,
        "ModifyIndex": 0
    }
}
```

2017-11-08 13:02 UTC, Gerrrr commented
>  set convert-dashes-to-underscores = true and defined two parameters:
>
>   secret_parameter
>  secret-parameter inside an if
>
> Then I didn't receive a warning, maybe because the secret-parameter is inside the if? Is that expectec behaviour? Update: of course it is because if it is - it was not inside an if. So if we want to use - legacy parameters they cannot be used in Jinja specific constructs, right? Actually this will render three parameters: secret_parameter, secret, and parameter.

We have `convert-dashes-to-underscores` option to convert dashes that were before considered to be a part of the variable name to dashes because Jinja2 would think that those dashes are actually a subtraction operations. Before this PR the only allowed variable format was like `{{id}}`, so opening curly brackets, a variable name and closing curly brackets (**NB** that there are no spaces).

Broccoli raises warnings (or crashes, depending on the `convert-dashes-to-underscores` flag) if it finds a variable in the legacy format. In the job file you posted the variables `secret` and `parameter` are inside the `if` statement that was not supported before, so there is no reason to raise a warning. Following the same logic, there should be no warning for variable usage like `{{ secret-variable }}`.

2017-11-08 13:11 UTC, FRosner commented
>>  set convert-dashes-to-underscores = true and defined two parameters:
>>
>>   secret_parameter
>>  secret-parameter inside an if
>>
>> Then I didn't receive a warning, maybe because the secret-parameter is inside the if? Is that expectec behaviour? Update: of course it is because if it is - it was not inside an if. So if we want to use - legacy parameters they cannot be used in Jinja specific constructs, right? Actually this will render three parameters: secret_parameter, secret, and parameter.
>
> We have `convert-dashes-to-underscores` option to convert dashes that were before considered to be a part of the variable name to dashes because Jinja2 would think that those dashes are actually a subtraction operations. Before this PR the only allowed variable format was like `{{id}}`, so opening curly brackets, a variable name and closing curly brackets (**NB** that there are no spaces).
>
>Broccoli raises warnings (or crashes, depending on the `convert-dashes-to-underscores` flag) if it finds a variable in the legacy format. In the job file you posted the variables `secret` and `parameter` are inside the `if` statement that was not supported before, so there is no reason to raise a warning. Following the same logic, there should be no warning for variable usage like `{{ secret-variable }}`.

That's what I figured. Makes sense. Thank you!

2017-11-08 13:25 UTC, Gerrrr commented
>Just to check if I understood correctly. We render the template using Jinjava three times:
>
>   When the template is loaded, we render it without any bindings to see if there is an ID parameter
>    When the template is loaded, we render it again without any bindings just to extract the parameters
>    When the template is rendered, we render with all the bindings to generate the JSON

Right. First, we load it to find variables in the legacy format that can contain dashes. Then, we load it again to check if the `id` parameter is there. Then, we actually render the template with the instance information. So the first two parsings happen only once per template while the rendering happens for each template instance.

>Will the mechanism of extracting all variables still work even if they are not mentioned in the parameter infos? Will it extract only global (unbound) variables or also local ones (like the ones bound in a loop)?

Quick test:
```scala
      val template = "{{id}} {{ global_var }} {% for x in [1 2 3] %}{{x}}{% endfor %}"
      val jinjava = new Jinjava()
      val renderResult = jinjava.renderForResult(template, Map("id" -> "abc", "global_var" -> "456"))
      println(renderResult.getOutput)
      println(renderResult.getContext.getResolvedValues)
```

prints:

```
abc 456 123
[x, id, global_var]
```

So it returns both global and local variables. Should I introduce explicit variable annotation in the `template.conf` also in this PR?

2017-11-08 13:28 UTC, FRosner commented
>So it returns both global and local variables. Should I introduce explicit variable annotation in the `template.conf` also in this PR?

Does that mean that the UI will also show you an input field for `x`? What happens if you provide something there?

2017-11-08 15:50 UTC, Gerrrr commented
Yes, you are right. Nice catch! I am going to fix it.

2017-11-09 06:31 UTC, FRosner requested changes
> Yes, you are right. Nice catch! I am going to fix it.
Please do that. Please also document it in the ticket that this needs to be documented.

2017-11-09 06:31 UTC, FRosner commented on server/src/main/scala/de/frosner/broccoli/templates/TemplateSource.scala
> +      val matcher = variablePattern.matcher(templateString)
Why are we finding variables with dashes not only when we want to convert them?

2017-11-09 06:31 UTC, FRosner commented on server/src/main/scala/de/frosner/broccoli/templates/jinjava/JinjavaConfiguration.scala
> +final case class JinjavaConfiguration(
Why are we constructing so many `JinjavaConfig` objects? What is anyway happening here? You define a case class with all default parameters. Where is it injected? How can you change it?

2017-11-24 16:36 UTC, Gerrrr commented
> So it returns both global and local variables. Should I introduce explicit variable annotation in the template.conf also in this PR?
> 
> Does that mean that the UI will also show you an input field for x? What happens if you provide something there?

Since I am going to introduce explicit variable declaration in the `template.conf`, do we really need `convert-dashes-to-underscores` flag? If all the variables are to be reviewed anyway, they can be as well renamed. Broccoli can still validate while loading templates that the declared variables do not contain dashes.

2017-11-24 21:30 UTC, FRosner commented
> Since I am going to introduce explicit variable declaration in the template.conf, do we really need convert-dashes-to-underscores flag? If all the variables are to be reviewed anyway, they can be as well renamed. Broccoli can still validate while loading templates that the declared variables do not contain dashes.

Yes we do because the problem is not about reviewing and renaming taking effort, it is about the problem of template migration. Renaming it will make it a new variable and the UI has no support for upgrading like this. It will be a nightmare.

> So it returns both global and local variables. Should I introduce explicit variable annotation in the template.conf also in this PR?

I think we should because if we merge this PR otherwise we introduced a bug (the UI showing `x` as an input field although it is a locally bound variable).

2017-11-24 21:31 UTC, FRosner commented
How are you going to "introduce" explicit variable declaration? There is not much to introduce. You just have to get the variables that exist from there and we need to document that all variables need to exist there. Or am I missing something?

2018-02-23 11:58 UTC, FRosner commented
When starting Broccoli with this changes, instances which were previously created can't be loaded:

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[IllegalArgumentException: requirement failed: The given parameters values (Set(id, sleep-count, time)) need to match the ones in the template (Set(time, id, enabled)).]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$handle$1.applyOrElse(PlayRequestHandler.scala:129)
	at play.core.server.netty.PlayRequestHandler$$anonfun$handle$1.applyOrElse(PlayRequestHandler.scala:127)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:44)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:252)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:157)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: requirement failed: The given parameters values (Set(id, sleep-count, time)) need to match the ones in the template (Set(time, id, enabled)).
	at scala.Predef$.require(Predef.scala:224)
	at de.frosner.broccoli.models.Instance.requireParameterValueConsistency(Instance.scala:13)
	at de.frosner.broccoli.models.Instance.<init>(Instance.scala:20)
	at de.frosner.broccoli.models.Instance$$anonfun$4.apply(Instance.scala:36)
	at de.frosner.broccoli.models.Instance$$anonfun$4.apply(Instance.scala:36)
	at play.api.libs.functional.FunctionalBuilder$CanBuild3$$anonfun$apply$7.apply(Products.scala:77)
	at play.api.libs.functional.FunctionalBuilder$CanBuild3$$anonfun$apply$7.apply(Products.scala:77)
	at play.api.libs.json.JsResult$class.map(JsResult.scala:77)
	at play.api.libs.json.JsSuccess.map(JsResult.scala:9)
	at play.api.libs.json.Reads$$anonfun$map$1.apply(Reads.scala:46)
	at play.api.libs.json.Reads$$anonfun$map$1.apply(Reads.scala:46)
	at play.api.libs.json.Reads$$anon$8.reads(Reads.scala:126)
	at play.api.libs.json.JsValue$class.validate(JsValue.scala:18)
	at play.api.libs.json.JsObject.validate(JsValue.scala:76)
	at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
	at play.api.libs.json.JsObject.as(JsValue.scala:76)
	at de.frosner.broccoli.instances.storage.filesystem.FileSystemInstanceStorage$$anonfun$6.apply(FileSystemInstanceStorage.scala:44)
	at de.frosner.broccoli.instances.storage.filesystem.FileSystemInstanceStorage$$anonfun$6.apply(FileSystemInstanceStorage.scala:44)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at de.frosner.broccoli.instances.storage.filesystem.FileSystemInstanceStorage.readInstanceImpl(FileSystemInstanceStorage.scala:44)
	at de.frosner.broccoli.instances.storage.filesystem.FileSystemInstanceStorage$$anonfun$readInstancesImpl$2$$anonfun$apply$3.apply(FileSystemInstanceStorage.scala:74)
	at de.frosner.broccoli.instances.storage.filesystem.FileSystemInstanceStorage$$anonfun$readInstancesImpl$2$$anonfun$apply$3.apply(FileSystemInstanceStorage.scala:73)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at de.frosner.broccoli.instances.storage.filesystem.FileSystemInstanceStorage$$anonfun$readInstancesImpl$2.apply(FileSystemInstanceStorage.scala:73)
	at de.frosner.broccoli.instances.storage.filesystem.FileSystemInstanceStorage$$anonfun$readInstancesImpl$2.apply(FileSystemInstanceStorage.scala:79)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at de.frosner.broccoli.instances.storage.filesystem.FileSystemInstanceStorage.readInstancesImpl(FileSystemInstanceStorage.scala:73)
	at de.frosner.broccoli.instances.storage.InstanceStorage$$anonfun$readInstances$3$$anonfun$apply$3.apply(InstanceStorage.scala:50)
	at de.frosner.broccoli.instances.storage.InstanceStorage$$anonfun$readInstances$3$$anonfun$apply$3.apply(InstanceStorage.scala:50)
	at de.frosner.broccoli.instances.storage.InstanceStorage$class.de$frosner$broccoli$instances$storage$InstanceStorage$$ifNotClosed(InstanceStorage.scala:15)
	at de.frosner.broccoli.instances.storage.InstanceStorage$$anonfun$readInstances$3.apply(InstanceStorage.scala:49)
	at de.frosner.broccoli.instances.storage.InstanceStorage$$anonfun$readInstances$3.apply(InstanceStorage.scala:49)
	at de.frosner.broccoli.logging$.logExecutionTime(logging.scala:23)
	at de.frosner.broccoli.instances.storage.InstanceStorage$class.readInstances(InstanceStorage.scala:52)
	at de.frosner.broccoli.instances.storage.filesystem.FileSystemInstanceStorage.readInstances(FileSystemInstanceStorage.scala:13)
	at de.frosner.broccoli.instances.storage.filesystem.FileSystemInstanceStorage.readInstancesImpl(FileSystemInstanceStorage.scala:59)
	at de.frosner.broccoli.instances.storage.InstanceStorage$$anonfun$readInstances$1$$anonfun$apply$2.apply(InstanceStorage.scala:38)
	at de.frosner.broccoli.instances.storage.InstanceStorage$$anonfun$readInstances$1$$anonfun$apply$2.apply(InstanceStorage.scala:38)
	at de.frosner.broccoli.instances.storage.InstanceStorage$class.de$frosner$broccoli$instances$storage$InstanceStorage$$ifNotClosed(InstanceStorage.scala:15)
	at de.frosner.broccoli.instances.storage.InstanceStorage$$anonfun$readInstances$1.apply(InstanceStorage.scala:37)
	at de.frosner.broccoli.instances.storage.InstanceStorage$$anonfun$readInstances$1.apply(InstanceStorage.scala:37)
	at de.frosner.broccoli.logging$.logExecutionTime(logging.scala:23)
	at de.frosner.broccoli.instances.storage.InstanceStorage$class.readInstances(InstanceStorage.scala:40)
	at de.frosner.broccoli.instances.storage.filesystem.FileSystemInstanceStorage.readInstances(FileSystemInstanceStorage.scala:13)
	at de.frosner.broccoli.services.InstanceService.initializeInstancesMap(InstanceService.scala:152)
	at de.frosner.broccoli.services.InstanceService.de$frosner$broccoli$services$InstanceService$$instances(InstanceService.scala:171)
	at de.frosner.broccoli.services.InstanceService.getInstances(InstanceService.scala:232)
	at de.frosner.broccoli.controllers.InstanceController$$anonfun$list$3.apply(InstanceController.scala:162)
	at de.frosner.broccoli.controllers.InstanceController$$anonfun$list$3.apply(InstanceController.scala:162)
	at scala.Option.ge [...]

2018-02-23 12:00 UTC, FRosner commented
Is

```
    jinjava {
      fail-on-unknown-tokens = true
    }
```

working as expected?

2018-02-23 12:03 UTC, Gerrrr commented
Before merging this PR we need to document the breaking changes:

* `template.conf` must include all variables in the parameter section.
* template variables cannot contain dashes any longer because we render the templates with `jinja2` and it will treat dashes as a subtraction operation. If you still have dashes in the variable names, you need to set `broccoli.templates.convert-dashes-to-underscores` to `true`.

Further TODOs:

* Check that the examples in `README` and wiki still work, otherwise adapt them.
* Document new `broccoli.templates.jinjava` properties.

2018-02-23 12:04 UTC, FRosner commented
Regarding the doc change, please copy the corresponding wiki section into the ticket (#224), change it the way it needs to be so we can include it later.

2018-02-23 12:07 UTC, FRosner commented
I found the following problem, which will encounter users when upgrading:

1. Add new template: [sleep.zip](https://github.com/FRosner/cluster-broccoli/files/1751564/sleep.zip)
2. Add new instances: [instances.zip](https://github.com/FRosner/cluster-broccoli/files/1751569/instances.zip)
3. Enable dash-conversion
3. Start Broccoli in the new version (this PR)
4. ```13:00:54.974 [ERROR] [pool-13-thread-1] [d.f.b.services.InstanceService] - Failed to load the instances: java.lang.IllegalArgumentException: requirement failed: The given parameters values (Set(id, sleep-count, time)) need to match the ones in the template (Set(time, id, enabled)).```

2018-02-23 12:09 UTC, Gerrrr commented
>Is
>
>    jinjava {
>      fail-on-unknown-tokens = true
>    }
>
> working as expected?

It is the option to set a jinjava's `failOnUnknownTokens` flag. From jinjava's [changelog](https://github.com/HubSpot/jinjava/blob/ff924a8752b741116c03505a02e6568276019c37/CHANGES.md#L98): 
> added failOnUnknownTokens mode which is similar to Jinja's StrictUndefined

Here is the behavior of Jinja's `StrictUndefined` ([source](http://jinja.pocoo.org/docs/2.10/api/)):
> StrictUndefined which disallows all operations beside testing if it’s an undefined object.

AFAIU it throws an exception while rendering if a tag or a variable is not defined in the scope.

2018-03-13 16:18 UTC, Gerrrr commented
Documentation changes:

https://github.com/FRosner/cluster-broccoli/wiki/Upgrading-to-0.8.0

**Templates**

Templates are now rendered with [Jinjava template engine](https://github.com/HubSpot/jinjava). Because of this, there are several changes breaking backwards compatibility:
* Variables can no longer contain dashes. In order to automatically convert dashes in the variable names in instances and templates, you can set `broccoli.templates.convert-dashes-to-underscores` to `true`.
* Broccoli no longer automatically discovers template variables. You have to explicitly specify all variables in `template.conf`. To fix existing instances, please run the upgrade script:
    - `nomad stop cluster-broccoli`
    - `python script/instances-0.7.0-to-0.8.0.py /path/to/broccoli/instances`
    - `nomad start cluster-broccoli`

**Configuration Changes**

It is possible to set [Jinjava config settings](https://static.javadoc.io/com.hubspot.jinjava/jinjava/2.4.0/index.html?com/hubspot/jinjava/JinjavaConfig.html) through Broccoli. The default values are kept the same as in Jinjava, unless stated otherwise. For documentation on those parameters please refer to the original project https://github.com/HubSpot/jinjava.

Here is the list of Jinjava settings configurable through Broccoli:

* `broccoli.templates.jinjava.charset`
* `broccoli.templates.jinjava.locale`
* `broccoli.templates.jinjava.time-zone`
* `broccoli.templates.jinjava.max-render-depth`
* `broccoli.templates.jinjava.trim-blocks`
* `broccoli.templates.jinjava.lstrip-blocks`
* `broccoli.templates.jinjava.read-only-resolver`
* `broccoli.templates.jinjava.enable-recursive-macro-calls`
* `broccoli.templates.jinjava.fail-on-unknown-tokens` (defaults to `true`)
* `broccoli.templates.jinjava.max-output-size`
* `broccoli.templates.jinjava.nested-interpretation-enabled`

---

https://github.com/FRosner/cluster-broccoli/wiki/Templates


#### Parameter Information

The template file usually contains different parameters. These parameters must be declared in the meta information file. They can also have additional properties.

2018-03-13 23:05 UTC, FRosner commented
I can't seem to find the config values you put here in the `reference.conf` file. Should we put them there? IMHO the reference configuration should contain all defaults.

2018-03-14 09:34 UTC, Gerrrr commented
You are right, it is actually a good idea. I'll add the jinjava config values to `reference.conf`.

2018-04-25 14:36 UTC, sohaibiftikhar reviewed
I fixed partially in a [commit](https://github.com/FRosner/cluster-broccoli/pull/311/commits/0ccab551302a6f62392157e4268ac2565b59a065).

2018-04-25 14:36 UTC, sohaibiftikhar commented on server/src/main/scala/de/frosner/broccoli/services/InstanceService.scala
> +      require(!templateRenderer.renderForResult(newInstance).hasErrors)
@Gerrrr Should we have more meaningful errors here? If this condition fails the frontend shows "requirement failed" which does not look very helpful.

2018-04-26 10:59 UTC, FRosner requested changes
LGTM. As discussed we should add proper validation of parameter names in the `template.conf` during template parsing.

2018-04-26 10:59 UTC, FRosner commented on server/src/main/scala/de/frosner/broccoli/templates/TemplateRenderer.scala
> +  def renderForResult(instance: Instance): RenderResult = {
Can we make some of the methods private?

2018-04-26 10:59 UTC, FRosner commented on server/src/main/scala/de/frosner/broccoli/templates/TemplateRenderer.scala
> +    if (!fatalErrors.isEmpty()) {
should be `fatalErrors.nonEmpty` instead, without braces

2018-04-26 10:59 UTC, FRosner commented on server/src/main/resources/reference.conf
>      # jinjava configuration
Sorry to bug again. Can we put a bit more documentation? I understand that we don't want to duplicate the Jinjava documentation here but at least link to it or make it more obvious where to look for the explanation of those values?

2018-04-26 10:59 UTC, FRosner commented on server/src/main/resources/reference.conf
>      # jinjava configuration
Also write what this part is used for. If you see the Jinjava block, it's not obvious if you need to configure it or so. In HOCON you can make block comments as well if you feel like it I think.

2018-04-26 10:59 UTC, FRosner commented on server/src/main/scala/de/frosner/broccoli/services/InstanceService.scala
> +      require(!templateRenderer.renderForResult(newInstance).hasErrors)
Yes please add a meaningful error message.

2018-04-27 08:22 UTC, FRosner approved these changes

2018-04-27 08:23 UTC, merged